---

- name: Provision s6-ssh
  hosts: localhost
#  become: yes
#  become_method: sudo
#  become_user: root

  tasks:
    - name: compiler base
      include_role:
        name: c-compiler-base
      vars:
        ansible_distribution: "{{ lookup('env','ANSIBLE_DISTRIBUTION') }}"

