# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source


variable "dockerhub_username" {
  type = string
}

variable "dockerhub_password" {
  type = string
}


source "docker" "docker-source" {
  changes = ["ENTRYPOINT [\"/init\"]", "EXPOSE 22 4000"]
  commit  = true
#  image   = "jalbert/ubuntu:22.04"
  image   = "jalbert/ubuntu:20.04"
  volumes = {"/home/a/temp/packer": "/home/app/temp"}
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.docker.docker-source"]

  provisioner "ansible" {
    ansible_env_vars = ["ANSIBLE_DISTRIBUTION=debian"]
    playbook_file    = "provision-python.yml"
    user             = "root"
  }

  post-processors {

    post-processor "docker-tag" {
      repository = "docker.io/jalbert/python"
#      tags       = ["ubuntu22"]
      tags       = ["ubuntu20"]
      force      = true
    }

    post-processor "docker-push" {
      login          = true
      login_username = var.dockerhub_username
      login_password = var.dockerhub_password
    }

     post-processor "shell-local" {
      inline = ["SUDO_ASKPASS=./asker sudo -A rm -r /home/a/temp/packer/*"]
     }

  }

}
