
[network]
# https://github.com/containers/podman/blob/main/docs/source/markdown/options/network.md?plain=1#L36
#default_rootless_network_cmd = "slirp4netns"
# https://github.com/containers/podman/blob/main/test/e2e/config/containers.conf#L63
#network_cmd_options = [ "allow_host_loopback=true" ] # not working

# https://github.com/containers/podman/blob/main/docs/source/markdown/options/network.md?plain=1#L63
pasta_options = ["--map-gw"]
