#!/usr/bin/env bash

arch=`uname -m`
#kernel_path=/media/a/data/installers/P/microservices/VMs/firecracker/vmlinux.bin
#firecraker_socker_path=/home/a/src/vm/firecracker.socket

if [ ${arch} = "x86_64" ]; then
    curl --unix-socket $firecraker_socker_path -i \
      -X PUT 'http://localhost/boot-source'   \
      -H 'Accept: application/json'           \
      -H 'Content-Type: application/json'     \
      -d "{
            \"kernel_image_path\": \"${kernel_path}\",
            \"boot_args\": \"console=ttyS0 reboot=k panic=1 pci=off\"
       }"
elif [ ${arch} = "aarch64" ]; then
    curl --unix-socket $firecraker_socker_path -i \
      -X PUT 'http://localhost/boot-source'   \
      -H 'Accept: application/json'           \
      -H 'Content-Type: application/json'     \
      -d "{
            \"kernel_image_path\": \"${kernel_path}\",
            \"boot_args\": \"keep_bootcon console=ttyS0 reboot=k panic=1 pci=off\"
       }"
else
    echo "Cannot run firecracker on $arch architecture!"
    exit 1
fi