#!/usr/bin/env bash

#rootfs_path=/media/a/data/installers/P/microservices/VMs/firecracker/bionic.rootfs.ext4
#firecraker_socker_path=/home/a/src/vm/firecracker.socket

curl --unix-socket $firecraker_socker_path -i \
  -X PUT 'http://localhost/drives/rootfs' \
  -H 'Accept: application/json'           \
  -H 'Content-Type: application/json'     \
  -d "{
        \"drive_id\": \"rootfs\",
        \"path_on_host\": \"${rootfs_path}\",
        \"is_root_device\": true,
        \"is_read_only\": false
   }"