---
- name: Creating public key dir if not exists
  raw: "mkdir -p $(dirname {{ lookup('env','PUBLIC_KEY_PATH') }})"

- name: setting public key
  copy:
    content: "{{ lookup('aws_secret', 'janus/public_key') }}"
    dest: "{{ lookup('env','PUBLIC_KEY_PATH') }}"

- name: Creating private key dir if not exists
  raw: "mkdir -p $(dirname {{ lookup('env','PRIVATE_KEY_PATH') }})"

- name: setting private key
  copy:
    content: "{{ lookup('aws_secret', 'janus/private_key') }}"
    dest: "{{ lookup('env','PRIVATE_KEY_PATH') }}"
