
# Global options:
# https://mypy.readthedocs.io/en/stable/config_file.html
# https://mypy.readthedocs.io/en/stable/common_issues.html
# https://mypy.readthedocs.io/en/stable/error_codes.html
# https://mypy.readthedocs.io/en/latest/error_code_list.html


[mypy]
warn_return_any = False
warn_unused_configs = False
#disable_error_code = import-untyped, var-annotated, has-type, assignment, arg-type, attr-defined, union-attr, valid-type, override, index, misc, list-item, empty-body, return-value, call-overload, type-arg
#enable_error_code = import-not-found, no-redef

# Enables PEP 420 style namespace packages. (default: True)
namespace_packages = False
# This flag tells mypy that top-level packages will be based in either the current directory, or a member of the MYPYPATH environment variable or mypy_path config option. This option is only useful in the absence of __init__.py.
# (default: False)
explicit_package_bases = False
# Suppresses error messages about imports that cannot be resolved.
# (default: False)
ignore_missing_imports = False
# Directs what to do with imports when the imported module is found as a .py file and not part of the files, modules and packages provided on the command line.
# The four possible values are normal, silent, skip and error. For explanations see the discussion for the --follow-imports command line flag.
# (default: normal)
follow_imports = normal
# Determines whether to respect the follow_imports setting even for stub (.pyi) files.
# Used in conjunction with follow_imports=skip, this can be used to suppress the import of a module from typeshed, replacing it with Any.
# Used in conjunction with follow_imports=error, this can be used to make any use of a particular typeshed module an error.
# (default: False)
follow_imports_for_stubs = False
# Disables using type information in installed packages (see PEP 561). This will also disable searching for a usable Python executable. This acts the same as --no-site-packages command line flag.
# (default: False)
no_site_packages = False
no_silence_site_packages = False
# Disallows usage of types that come from unfollowed imports (anything imported from an unfollowed import is automatically given a type of Any).
# (default: False)
disallow_any_unimported = False
# Disallows all expressions in the module that have type Any.
# (default: False)
disallow_any_expr = False
# Disallows functions that have Any in their signature after decorator transformation.
# (default: False)
disallow_any_decorated = False
# Disallows explicit Any in type positions such as type annotations and generic type parameters.
# (default: False)
disallow_any_explicit = False
# Disallows usage of generic types that do not specify explicit type parameters.
# (default: False)
disallow_any_generics = False
# Disallows subclassing a value of type Any.
# (default: False)
disallow_subclassing_any = False
# https://mypy.readthedocs.io/en/stable/config_file.html#untyped-definitions-and-calls
# (default: False)
disallow_untyped_calls = False
# Disallows defining functions without type annotations or with incomplete type annotations (a superset of disallow_incomplete_defs).
# (default: False)
disallow_untyped_defs = False
# Disallows defining functions with incomplete type annotations, while still allowing entirely unannotated definitions.
# (default: False)
disallow_incomplete_defs = False
# Type-checks the interior of functions without type annotations.
# (default: False)
check_untyped_defs = False
# Reports an error whenever a function with type annotations is decorated with a decorator without annotations.
# (default: False)
disallow_untyped_decorators = False
# Causes mypy to treat parameters with a None default value as having an implicit optional type (T | None).
# (default: False)
implicit_optional = False
# Effectively disables checking of optional types and None values. With this option, mypy doesn’t generally check the use of None values – it is treated as compatible with every type.
#
# (default: True)
strict_optional = True
# Allows variables to be redefined with an arbitrary type, as long as the redefinition is in the same block and nesting level as the original definition.
# (default: False)
allow_redefinition = True
