#!/usr/bin/env bash
set -e
set -u
set -o pipefail

this_dir="$(dirname "$0")"
repo_home_dir="$(cd "$this_dir" && cd . && pwd)"

rm $HOME/.local/share/applications/Logseq.desktop 2>/dev/null || true

cd "$repo_home_dir"

cd base
#https://www.gnu.org/software/stow/manual/html_node/Resource-Files.html
stow \
  -t "$HOME" \
  broot \
  kitty \
  zellij \
  yazi \
  bin

#  superfile \
#  wezterm \

cd ../data
stow \
  -t "$HOME" \
  jq \
  bin

cd ../dev
stow \
  -t "$HOME" \
  clojure \
  coursier \
  efm \
  lazygit \
  git \
  js \
  poetry \
  sbt \
  sqlfluff \
  tree-sitter-cli \
  uv \
  bin


cd ../editors
stow \
  -t "$HOME" \
  emacs-dev-bridge \
  emacs-dev-lsp \
  emacs-dev-eglot \
  emacs-doom \
  emacs-writer \
  nvim \
  nvim-dev \
  nvim-vscode \
  nvim-lazy \
  jetbrains-vim

cd ../extra
stow \
  -t "$HOME" \
  hledger

cd ../lnx-utils
stow \
  -t "$HOME" \
  debian-aptly \
  distrobox \
  files-utils \
  notifications \
  ov \
  procs \
  bin

cd ../local
stow \
  -t "$HOME" \
  qmk

cd ../medias
stow \
  -t "$HOME" \
  mpd \
  rmpc

cd ../Ops
stow \
  -t "$HOME" \
  containers \
  direnv \
  just \
  k9s \
  qtile \
  rofi \
  bin

#  tmux \
#  tmuxp \
#  byobu \

cd ../shells
stow \
  -t "$HOME" \
  atuin \
  carapace \
  cheat \
  navi \
  nushell \
  starship \
  tealdeer \
  television \
  fish

cd ../study
stow \
  -t "$HOME" \
  bin \
  espanso \
  harper \
  logseq \
  obs-studio \
  sioyek \
  vale

cd ../GUIs
stow \
  -t "$HOME" \
  base \
  data \
  dev \
  hobbies \
  media \
  security \
  learning \
  writing
