
CREATE USER 'app-user' IDENTIFIED BY 'dpass';
CREATE USER 'admin-user' IDENTIFIED BY 'dpass';

GRANT INSERT, SELECT, SHOW VIEW, UPDATE ON *.* TO 'app-user' WITH GRANT OPTION;
GRANT INSERT, CREATE, SELECT, SHOW VIEW, UPDATE, ALTER ON *.* TO 'admin-user' WITH GRANT OPTION;

