#!/usr/bin/env bash

if [ -z ${USING_HOOKS+x} ]; then
  :
else
  if [ "$USING_HOOKS" = "true" ]; then
    for cmd in $(yq '.hooks | .pre-commit' .hooks-config.yaml); do
      eval "$cmd $@"
    done
  fi
fi
