fish_vi_key_bindings

# set fish_function_path $fish_function_path "/usr/share/powerline/bindings/fish"
# source /usr/share/powerline/bindings/fish/powerline-setup.fish

source ~/.config/fish/conf.d/env_vars.fish
source ~/.config/fish/conf.d/functions.fish
source ~/.config/fish/conf.d/inits.fish
source ~/.config/fish/conf.d/al.fish
source ~/.config/fish/conf.d/fzf-git.fish

#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# set -x NVM_DIR "$HOME/.nvm"
# bass source "$NVM_DIR/nvm.sh" ';' # This loads nvm

#bass source ~/.nvm/nvm.sh --no-use ';' 

# function nvm
# nvm $argv
# end

# theme
set -g theme_color_scheme terminal-dark
set -g fish_prompt_pwd_dir_length 1
set -g theme_display_user yes
set -g theme_hide_hostname no
set -g theme_hostname always
set -gx TERM xterm-256color

# powerline-setup

set -g fish_greeting
# set -g IDEA_PROPERTIES '/usr/local/bin/appslnx/jetbrains/idea/personal/idea.properties'

set -x LD_LIBRARY_PATH /usr/local/lib/

# source /media/z/data/installers/Unix/CLI-tools/tmuxinator/completion/tmuxinator.fish

# https://github.com/rbenv/rbenv
# set -x fish_user_paths $HOME/.rbenv/bin $fish_user_paths
# status --is-interactive; and source (rbenv init -|psub)

# set -x PATH $HOME/appslnx/bin/job $PATH
penv

# set -x _ZO_DATA_DIR /media/z/data/repo/zoxide
set -x _ZO_ECHO 1

# zoxide init fish | source # now in ~/.config/fish/conf.d/inits.fish
direnv hook fish | source
# Install Starship
starship init fish | source
# Configure Jump
status --is-interactive; and source (jump shell fish | psub)
fzf --fish | source
# mise activate fish | source
uv generate-shell-completion fish | source


# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br --wraps=broot
    set -l cmd_file (mktemp)
    if broot --outcmd $cmd_file $argv
        source $cmd_file
        rm -f $cmd_file
    else
        set -l code $status
        rm -f $cmd_file
        return $code
    end
end

# https://docs.atuin.sh/cli/configuration/key-binding/?h=fish#fish
# set -gx ATUIN_NOBIND "true"

# The command bind -M insert \e[A _atuin_bind_up in your fish config means:
# bind: This is the fish shell command to create or modify key bindings.
# -M insert: This specifies the key binding mode. "insert" mode is the default mode when you are typing a command.
# \e[A: This is the escape sequence for the Up Arrow key (in many terminals).
# _atuin_bind_up: This is the fish function or command to execute when the Up Arrow key is pressed in insert mode.

atuin init fish | source
# bind to ctrl-r in normal and insert mode, add any other bindings you want here too
bind -M insert \cr _atuin_search
bind -M insert \e\[A _atuin_bind_up

if status is-interactive
    #     eval (zellij setup --generate-auto-start fish | string collect)
end

# bind \cr history-token-search-backward
# bind \cn history-token-search-forward
# bind \cg "commandline -rt (complete -C --escape|fzf|cut -d\t -f1)\ "

# Fish syntax highlighting
set -g fish_color_autosuggestion 555 brblack
set -g fish_color_cancel -r
set -g fish_color_command --bold
set -g fish_color_comment red
set -g fish_color_cwd green
set -g fish_color_cwd_root red
set -g fish_color_end brmagenta
set -g fish_color_error brred
set -g fish_color_escape bryellow --bold
set -g fish_color_history_current --bold
set -g fish_color_host normal
set -g fish_color_match --background=brblue
set -g fish_color_normal normal
set -g fish_color_operator bryellow
set -g fish_color_param cyan
set -g fish_color_quote yellow
set -g fish_color_redirection brblue
set -g fish_color_search_match bryellow '--background=brblack'
set -g fish_color_selection white --bold '--background=brblack'
set -g fish_color_user brgreen
set -g fish_color_valid_path --underline

if status is-interactive
    # Commands to run in interactive sessions can go here
end

