# Example using filters, ignoring permission errors, and specifying the hostname precedence
plugin: aws_secret
# Populate inventory with instances in these regions
regions:
  - eu-west-1

# Ignores 403 errors rather than failing
strict_permissions: False
