central.from=https://repo1.maven.org/maven2
central.to=http://localhost:8080/releases

jcenter.from=https://repo1.maven.org/maven2
jcenter.to=http://localhost:8080/releases

typesafe.from=https://repo.typesafe.com/typesafe/ivy-releases
typesafe.to=http://localhost:8080/releases
