BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
COMMAND_ENABLE = yes
NKRO_ENABLE = yes
#UNICODE_ENABLE = yes
#UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=FALSE
