
app{
    images{
        postgres_15 = "postgres:15.15-alpine3.22"
        postgres_16 = "postgres:16.10-alpine3.22"
        postgres_17 = "postgres:17.6-alpine3.22"
        postgres_18 = "postgres:18.1-alpine3.22"
        postgres_debian = "postgres:18.1-trixie"
        postgis = "postgis/postgis:18-3.6-alpine"
        mariadb = "mariadb:12.0.2-noble"
        mysql = "mysql:9.4.0"
        redpanda = "docker.redpanda.com/redpandadata/redpanda:v25.2.1"
        redpanda_console = "docker.redpanda.com/redpandadata/console:v3.1.3"
        cassandra = "cassandra:5.0.5"
        latex = "danteev/texlive:2025-08-15"
        registry = "registry:3.0.0"
        dnsmasq = "dockurr/dnsmasq:2.90"
        traefik= "traefik:v3.5.3"
        rabbitmq= "rabbitmq:4.1.3-management-alpine"
        xtdb = "ghcr.io/xtdb/xtdb:2.0.0"
        stirlingtools = "docker.stirlingpdf.com/stirlingtools/stirling-pdf:1.5.0-fat"
        penpotapp_frontend= "penpotapp/frontend:2.11.1"
        penpotapp_backend= "penpotapp/backend:2.11.1"
        penpotapp_exporter= "penpotapp/exporter:2.11.1"
        penpotapp_mailcatch= "sj26/mailcatcher:v0.10.0"
        valkey = "valkey/valkey:8.1"
    }
}
