.TH "kitten-command-palette" "1" "Mar 21, 2026" "0.46.2" "kitten Manual"
.SH Name
kitten-command-palette \- Browse and trigger keyboard shortcuts and actions
.SH Usage
.SY "kitten command-palette "
.YS
.SH Description
Browse and trigger keyboard shortcuts and actions
.SH Options
.TP
.BI "--help, -h" " [=no]"
Show help for this command
