.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-gray 1  "gray " 
.SH NAME
pastel\-gray \- Create a gray tone from a given lightness
.SH SYNOPSIS
\fBpastel gray\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIlightness\fR> 
.SH DESCRIPTION
Create a gray tone from a given lightness value.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIlightness\fR>
Lightness of the created gray tone (number between 0.0 and 1.0)
