.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-list 1  "list " 
.SH NAME
pastel\-list \- Show a list of available color names
.SH SYNOPSIS
\fBpastel list\fR [\fB\-s\fR|\fB\-\-sort\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show a list of available color names
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-sort\fR [default: hue]
Sort order
.br

.br
[\fIpossible values: \fRbrightness, luminance, hue, chroma, random]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
