.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-desaturate 1  "desaturate " 
.SH NAME
pastel\-desaturate \- Decrease color saturation by a specified amount
.SH SYNOPSIS
\fBpastel desaturate\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIamount\fR> [\fIcolor\fR] 
.SH DESCRIPTION
Decrease the saturation of a color by subtracting a certain amount from the HSL saturation channel. If the amount is negative, the color will be saturated instead.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIamount\fR>
Amount of saturation to subtract (number between 0.0 and 1.0)
.TP
[\fIcolor\fR]
Colors can be specified in many different formats, such as #RRGGBB, RRGGBB, #RGB, \*(Aqrgb(…, …, …)\*(Aq, \*(Aqhsl(…, …, …)\*(Aq, \*(Aqgray(…)\*(Aq or simply by the name of the color. The identifier \*(Aq\-\*(Aq can be used to read a single color from standard input. Also, the special identifier \*(Aqpick\*(Aq can be used to run an external color picker to choose a color. If no color argument is specified, colors will be read from standard input.
Examples (all of these specify the same color):
  \- lightslategray
  \- \*(Aq#778899\*(Aq
  \- 778899
  \- 789
  \- \*(Aqrgb(119, 136, 153)\*(Aq
  \- \*(Aq119,136,153\*(Aq
  \- \*(Aqhsl(210, 14.3%, 53.3%)\*(Aq
Alpha transparency is also supported:
  \- \*(Aq#77889980\*(Aq
  \- \*(Aqrgba(119, 136, 153, 0.5)\*(Aq
  \- \*(Aqhsla(210, 14.3%, 53.3%, 50%)\*(Aq
