.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-color 1  "color " 
.SH NAME
pastel\-color \- Display information about the given color
.SH SYNOPSIS
\fBpastel color\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIcolor\fR] 
.SH DESCRIPTION
Show and display some information about the given color(s).
.PP
Example:
  pastel color 556270 4ecdc4 c7f484 ff6b6b c44d58
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIcolor\fR]
Colors can be specified in many different formats, such as #RRGGBB, RRGGBB, #RGB, \*(Aqrgb(…, …, …)\*(Aq, \*(Aqhsl(…, …, …)\*(Aq, \*(Aqgray(…)\*(Aq or simply by the name of the color. The identifier \*(Aq\-\*(Aq can be used to read a single color from standard input. Also, the special identifier \*(Aqpick\*(Aq can be used to run an external color picker to choose a color. If no color argument is specified, colors will be read from standard input.
Examples (all of these specify the same color):
  \- lightslategray
  \- \*(Aq#778899\*(Aq
  \- 778899
  \- 789
  \- \*(Aqrgb(119, 136, 153)\*(Aq
  \- \*(Aq119,136,153\*(Aq
  \- \*(Aqhsl(210, 14.3%, 53.3%)\*(Aq
Alpha transparency is also supported:
  \- \*(Aq#77889980\*(Aq
  \- \*(Aqrgba(119, 136, 153, 0.5)\*(Aq
  \- \*(Aqhsla(210, 14.3%, 53.3%, 50%)\*(Aq
