.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-colorcheck 1  "colorcheck " 
.SH NAME
pastel\-colorcheck \- Check if your terminal emulator supports 24\-bit colors.
.SH SYNOPSIS
\fBpastel colorcheck\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check if your terminal emulator supports 24\-bit colors.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
