.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pastel-textcolor 1  "textcolor " 
.SH NAME
pastel\-textcolor \- Get a readable text color for the given background color
.SH SYNOPSIS
\fBpastel textcolor\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIcolor\fR] 
.SH DESCRIPTION
Return a readable foreground text color (either black or white) for a given background color. This can also be used in the opposite way, i.e. to create a background color for a given text color.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIcolor\fR]
Colors can be specified in many different formats, such as #RRGGBB, RRGGBB, #RGB, \*(Aqrgb(…, …, …)\*(Aq, \*(Aqhsl(…, …, …)\*(Aq, \*(Aqgray(…)\*(Aq or simply by the name of the color. The identifier \*(Aq\-\*(Aq can be used to read a single color from standard input. Also, the special identifier \*(Aqpick\*(Aq can be used to run an external color picker to choose a color. If no color argument is specified, colors will be read from standard input.
Examples (all of these specify the same color):
  \- lightslategray
  \- \*(Aq#778899\*(Aq
  \- 778899
  \- 789
  \- \*(Aqrgb(119, 136, 153)\*(Aq
  \- \*(Aq119,136,153\*(Aq
  \- \*(Aqhsl(210, 14.3%, 53.3%)\*(Aq
Alpha transparency is also supported:
  \- \*(Aq#77889980\*(Aq
  \- \*(Aqrgba(119, 136, 153, 0.5)\*(Aq
  \- \*(Aqhsla(210, 14.3%, 53.3%, 50%)\*(Aq
