---

- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap Python
      raw: apt-get -y update && apt-get install -y python3-minimal

- name: Provision Git, unzip
  hosts: all
  gather_facts: no
  tasks:
    - name: Install git and unzip
      raw: apt-get install -y git unzip software-properties-common

- name: Provision Hugo
  hosts: all

  vars:
    ruby_gems:
      - asciidoctor:2.0.23
      - asciidoctor-diagram:2.3.1

  tasks:
    - name: Install Node
      include_tasks: "../tasks/install-nodejs.yaml"

    - name: Install Hugo
      include_tasks: "../tasks/install-hugo.yaml"

    - name: Install asciidoctor
      include_tasks: "../tasks/install-asciidoctor.yaml"

