set shell := ["sh", "-c"]
set allow-duplicate-recipes := true
set positional-arguments := true
set dotenv-load := true
set export := true

# default: compile

infrastructure-up:
      mkdir -p logs/var/vector
lstart:
    #!/usr/bin/env bash
    set -euxo pipefail

    vector -c support/observability/vector/vector.toml &
    echo $! > .vector.pid

lstop:
    #!/usr/bin/env bash
    set -euxo pipefail

    kill -9 $(cat .vector.pid)
    rm .vector.pid
