#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Create container
      docker_container:
        name: elixir-machine-service
#        ubuntu:18.04
        image: "ubuntu:18.04"
        detach: true
        interactive: true
        tty: true
        debug: yes
#        env:
#          UPDATE_USER_IDS: "yes"
#          CONTAINER_COMMAND: "make release"
#          CLEAN_COMPILATION_DIRS: "yes"
#          USING_CONSUL: "no"
#          GET_IDS_USING_CONSUL: "no"
#          CONSUL_ADDR: "172.17.0.2:8500"
#          CONSUL_PREFIXES: "-prefix app-config-"
#        volumes:
#          - "{{ src_path }}:/home/app/src"
#          - "{{ ssh_path }}:/home/app/.ssh"

    - name: Add docker container to inventory
      add_host:
        name: elixir-machine-service
        ansible_connection: docker
        ansible_user: root

- hosts: elixir-machine-service
  gather_facts: false

  tasks:
    - name: Boostrap Python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

    - name: Install pip
      raw: apt-get install -y python-pip

    - name: Install required libraries
      raw: pip install boto boto3 botocore

    - name: Putting pem files from secrets manager
      include_role:
        name: janus-pem

# PUBLIC_KEY_PATH=/home/ubuntu/public.pem PRIVATE_KEY_PATH=/home/ubuntu/private.pem aws-vault exec admin -- ./get-janus-keys.yml

#- hosts: localhost
#  gather_facts: false
#
#  tasks:
#    - name: destroy container
#      docker_container:
#        name: elixir-machine-service
#        state: absent
