# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#      - alertmanager.service.dc1.consul:9093
#
#rule_files:
#  - "/alertmanager/alert.rules.yml"

scrape_configs:

  - job_name: betika-dev

    static_configs:
    - targets:
        - 'host.docker.internal:6032'
#        - 'host.docker.internal:9095'
#      - 'host.docker.internal:4000'

#  - job_name: paygate
#
#    static_configs:
#      - targets:
#          - 'host.docker.internal:4002'

#  - job_name: client
#
#    static_configs:
#      - targets:
#          - 'host.docker.internal:4003'
#
#  - job_name: provider
#
#    static_configs:
#      - targets:
#          - 'host.docker.internal:4004'
